name: 'Build image on push to master'
run-name: Build image on push to master by @${{ github.actor }}

on:
  push:
    branches:
      - sample-build-pipeline

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            "vocovo/docker-mosquitto:${{ github.sha }}"
            "vocovo/docker-mosquitto:latest"
